export const lectureNames = [
'3D Computer Graphics and Realism',
'3D Object Retrieval',
'Adaptive Systems',
'Advanced and Algorithmic Graph Theory',
'Advanced Information Theory',
'Advanced Robotics',
'Advanced Topics in Artificial Intelligence',
'Advanced Topics in Software Testing',
'Agile Software Development',
'Algorithms and Games',
'Analytic Combinatorics',
'Application of Innovative Technologies',
'Applications of Innovative Technologies',
'Applied Statistics',
'Architecture of Database Systems',
'Architecture of Machine Learning Systems',
'Augmented Reality',
'Automatic Speech Recognition',
'Autonomously Learning Systems',
'Camera Drones',
'Cloud Operating Systems',
'Coding and Cryptography',
'Combinatorial optimisation 2',
'Combinatorial Optimization',
'Compiler Construction',
'Complexity Theory',
'Computational Social Systems 1',
'Computational Social Systems 2',
'Computational Statistics',
'Computer Aided Geometric Design',
'Computer Aided System Modeling and Simulation',
'Configuration Systems',
'Context-Aware Computing',
'Context-Aware-Computing',
'Control Systems 1',
'Control Systems 2',
'Convex Optimization',
'Critical Readings in Data Science',
'Cryptanalysis',
'Cryptography',
'Data Analysis and Introduction to R',
'Data Integration and Large-Scale Analysis',
'Deep Learning',
'Design Patterns',
'Design Thinking and Rapid Prototyping',
'Designing Interactive Systems',
'Digital Libraries',
'Digital System Integration and Programming',
'Digital Systen Design',
'Discrete and Computational',
'Discrete Differential Geometry',
'Discrete Stochastics and Information Theory',
'Diskrete Differentialgeometrie',
'Einführung IT-Recht',
'Embedded Automotive Software',
'Embedded Internet',
'Embedded Systems',
'Entwurf und Analyse von Algorithmen',
'Enumerative Combinatoric Algorithms',
'Evaluation Methodology',
'Explanations in Artificial Intelligence',
'Fault-Tolerant Computing Systems',
'Fault-Tolerant Distributed Algorithms',
'Formal Specification and Design of Software',
'Fundamentals of Geometry Processing',
'Futurology',
'Game Design and Development',
'Game Design and Development II',
'Generalized Linear Models',
'Geometric 3D-Modeling in Computer Graphics',
'Geometric 3D-Modelling in Computer Graphics',
'Geometry for Computer Scientists',
'GPU Programming',
'Grundlagen der Artificial Intelligence und Logik',
'Hardware-Software-Codesign',
'HCI: Applying User-Centered Design',
'HCI: Applying User-Centred Design',
'Image and Video Understanding',
'Image Based Measurement',
'Image Based Measurement, Lab',
'Image Processing and Pattern Recognition',
'Industrial Software Development and Quality Management',
'Industrial Statistics',
'Industrieroboter',
'Information Architecture and Web Usability',
'Information Search and Retrieval',
'Information Theory and Coding',
'Information Visualization',
'Instructional Design in (Game-Based) Learning',
'Intelligent Systems',
'Intelligent User Interfaces',
'Introduction to Quantum Computing',
'Kinematics and Robotics',
'Knowledge Discovery & Data Mining',
'Knowledge Discovery & Data Mining 2',
'Laborübung Industrieroboter',
'Lineare Algebra',
'Lineare Algebra 2',
'Linguistic Foundations of Speech and Language Technology',
'Logic and Computability',
'Logic-Based Knowledge Representation',
'Machine Learning',
'Machine Learning 1',
'Machine Learning 2',
'Mathematical Principles in Visual Computing',
'Medical Image Analysis',
'Mobile Applications',
'Mobile Computing, Seminar',
'Mobile Robots',
'Mobile Security',
'Model Checking',
'Model-based Testing',
'Modelling Technical Systems',
'Natural Language Processing',
'Navigation Systems',
'Network Science',
'Nonlinear Optimization',
'Nonlinear Signal Processing',
'Number Theory',
'Numerical Optimization',
'Object-oriented Analysis and Design',
'Operations Research',
'Power-Aware Computing',
'Power-Aware Computing, Lab',
'Principles of Brain Computation',
'Privacy Enhancing Technologies',
'Probabilistic Method in Combinatorics and Algorithmics',
'Problem Analysis and Complexity Theory',
'Processor Architecture',
'Quality Assurance in Software Development',
'Qualitätssicherung in der Softwareentwicklung',
'Real-Time Graphics',
'Real-Time Operating Systems',
'Recommender Systems',
'Regression Analysis',
'Reinforcement Learning',
'Robot Vision',
'Science, Technology and Society: Core Concepts and Case Studies',
'Secure Application Design',
'Secure Product Lifecycle',
'Secure Software Development',
'Self-Optimisation and Digitalisation of the Body',
'Seminar Algorithm Design',
'Seminar Cryptology and Privacy',
'Seminar Data Science',
'Seminar Discrete Mathematics and Theory of Algorithms',
'Seminar Formal Methods',
'Seminar Pattern Recognition',
'Seminar Software Technology',
'Seminar Theoretical Computer Science',
'Seminar Visual Computing',
'Seminar/Project Algorithms',
'Seminar/Project Data Science',
'Seminar/Project Games Engineering',
'Seminar/Project Information Security',
'Seminar/Project Intelligent Systems',
'Seminar/Project Interactive and Visual Information Systems',
'Seminar/Project Software Technology',
'Seminar/Project Visual Computing',
'Sensor Networks',
'Sensor Networks, Lab',
'Side-Channel Security',
'Signal Processing',
'Simulation and Animation',
'Smart Service Development',
'Social Media Technologies',
'Social Media Technology',
'Software Engineering for Autonomous Robots',
'Software Technology',
'Software Technology Tools',
'Software Testing for Safety-Critical Systems',
'Software-Maintenance',
'Spatial Databases',
'Special Topics in STS – Science, Technology and Society',
'Speech Synthesis',
'Spoken Language in Human and Human-Computer Dialogue',
'State Estimation and Filtering',
'Statistik',
'Stochastic Simulation',
'Sustainability CS',
'Technical Numerics',
'Technical Numerics 2',
'Technik und Geschlecht',
'Technik – Ethik – Politik',
'Technikfolgenabschätzung',
'Technikgeschichte',
'Theoretische Informatik',
'Time Series Analysis',
'Topological Data Analysis',
'User Interfaces',
'Utopia and Dystopia of Technology',
'Verification and Testing',
'Virtual Reality',
'Visual Analytics',
'Visualization',
'Wearable Computing',
'Web Technology'
];
