export const lectureNames = [
'Entwurf und Analyse von Algorithmen',
'Problem Analysis and Complexity Theory',
'Algorithms and Games',
'Probabilistic Method in Combinatorics and Algorithmics',
'Advanced and Algorithmic Graph Theory',
'Geometry for Computer Scientists',
'Numerical Optimization',
'Convex Optimization',
'Operations Research',
'Combinatorial Optimization',
'Theoretische Informatik',
'Logic and Computability',
'Information Theory and Coding',
'Analytic Combinatorics',
'Complexity Theory',
'Machine Learning 1',
'Mathematical Principles in Visual Computing',
'Network Science',
'Verification and Testing',
'Number Theory',
'Model Checking',
'Formal Specification and Design of Software',
'Seminar/Project Algorithms',
'Seminar Discrete Mathematics and Theory of Algorithms',
'Seminar Algorithm Design',
'Seminar Theoretical Computer Science',
'Knowledge Discovery & Data Mining 2',
'Machine Learning 2',
'Deep Learning',
'Visual Analytics',
'Architecture of Database Systems',
'Spatial Databases',
'Privacy Enhancing Technologies',
'Computational Social Systems 1',
'Computational Social Systems 2',
'Recommender Systems',
'Information Search and Retrieval',
'Social Media Technologies',
'Evaluation Methodology',
'Critical Readings in Data Science',
'Industrial Statistics',
'Topological Data Analysis',
'Seminar/Project Data Science',
'Seminar Data Science',
'Advanced Topics in Artificial Intelligence',
'Mobile Applications',
'GPU Programming',
'Software Technology',
'Designing Interactive Systems',
'Information Architecture and Web Usability',
'HCI: Applying User-Centered Design',
'User Interfaces',
'Intelligent User Interfaces',
'Augmented Reality',
'Virtual Reality',
'3D Computer Graphics and Realism',
'Geometric 3D-Modeling in Computer Graphics',
'Seminar/Project Games Engineering',
'Cryptanalysis',
'Coding and Cryptography',
'Digital System Integration and Programming',
'Side-Channel Security',
'Cloud Operating Systems',
'Compiler Construction',
'Model-based Testing',
'Mobile Security',
'Secure Product Lifecycle',
'Fault-Tolerant Distributed Algorithms',
'Seminar Cryptology and Privacy',
'Seminar Formal Methods',
'Configuration Systems',
'Principles of Brain Computation',
'Adaptive Systems',
'Data Analysis and Introduction to R',
'Advanced Robotics',
'Context-Aware-Computing',
'Mobile Robots',
'Navigation Systems',
'Seminar/Project Intelligent Systems',
'Game Design and Development',
'Simulation and Animation',
'Visualization',
'Seminar/Project Interactive and Visual Information Systems',
'Applications of Innovative Technologies',
'Autonomously Learning Systems',
'Natural Language Processing',
'Camera Drones',
'Image Based Measurement',
'Software Engineering for Autonomous Robots',
'Design Thinking and Rapid Prototyping',
'Modelling Technical Systems',
'Embedded Systems',
'Intelligent Systems',
'Architecture of Machine Learning Systems',
'Web Technology',
'Agile Software Development',
'Object-oriented Analysis and Design',
'Software-Maintenance',
'Quality Assurance in Software Development',
'Industrial Software Development and Quality Management',
'Secure Software Development',
'Secure Application Design',
'Software Testing for Safety-Critical Systems',
'Advanced Topics in Software Testing',
'Seminar/Project Software Technology',
'Seminar Software Technology',
'Software Technology Tools',
'Discrete Differential Geometry',
'Image and Video Understanding',
'Medical Image Analysis',
'Information Visualization',
'Computer Aided Geometric Design',
'3D Object Retrieval',
'Seminar/Project Visual Computing',
'Seminar Visual Computing',
'Seminar Pattern Recognition',
'Lineare Algebra',
'Technical Numerics',
'Control Systems',
'Signal Processing',
'Applied Statistics',
'Computer Aided System Modeling and Simulation',
'State Estimation and Filtering',
'Stochastic Simulation',
'Regression Analysis',
'Generalized Linear Models',
'Time Series Analysis',
'Computational Statistics',
'Embedded Internet',
'Embedded Automotive Software',
'Real-Time Operating Systems',
'Sensor Networks',
'Processor Architecture',
'Context-Aware Computing',
'Fault-Tolerant Computing Systems',
'Power-Aware Computing',
'Mobile Computing, Seminar',
'Hardware-Software-Codesign',
'Smart Service Development',
'Science, Technology and Society: Core Concepts and Case Studies',
'Technik – Ethik – Politik',
'Technikfolgenabschätzung',
'Technik und Geschlecht',
'Futurology',
'Utopia and Dystopia of Technology',
'Self-Optimisation and Digitalisation of the Body',
'Technikgeschichte',
'Special Topics in STS – Science, Technology and Society',
'Robot Vision',
'Design Patterns',
'Real-Time Graphics',
'Cryptography',
'Machine Learning',
'Knowledge Discovery & Data Mining',
'Image Processing and Pattern Recognition',
'Geometric 3D-Modelling in Computer Graphics',
'Discrete Stochastics and Information Theory',
'Digital Libraries',
'Einführung IT-Recht',
'Statistik',
'Speech Synthesis',
'Automatic Speech Recognition',
'Sustainability CS',
'Nonlinear Signal Processing',
'Linguistic Foundations of Speech and Language Technology'
];